name: Build
on:
  release:
    types:
      - published

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: Setup Java 16
        uses: actions/setup-java@v2
        with:
          distribution: 'zulu'
          java-version: '16'
      - name: Grant Permissions to gradlew
        run: chmod +x gradlew
      - name: Build with Gradle
        run: ./gradlew build
